// <auto-generated />
namespace HTML_Parser.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NullParentWebPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullParentWebPage));
        
        string IMigrationMetadata.Id
        {
            get { return "201702101550583_NullParentWebPage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
