// <auto-generated />
namespace HTML_Parser.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReferralPageId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReferralPageId));
        
        string IMigrationMetadata.Id
        {
            get { return "201702131400298_ReferralPageId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
